#!/usr/bin/env bash

SERVER_DIR="/home/trainclock/TrainClock/server"
LOG="$SERVER_DIR/server.log"
SERVICE="trainclock.service"

case "$1" in
  start)
    "$0" stop
    sudo systemctl start "$SERVICE"
    echo "Started the server"
    ;;
  stop)
    sudo systemctl stop "$SERVICE"
    echo "Stoped the server"
    ;;
  status)
    sudo systemctl status "$SERVICE"
    ;;
  log)
    tail -f "$LOG"
    ;;
  initialize)
    "$SERVER_DIR"/initialize
    ;;
  *)
    echo "Usage: $0 {start|stop|status|log|initialize}"
    exit 1
    ;;
esac
