#!/usr/bin/env bash

IMAGE="trainclock_node_env"
CONTAINER_NAME="${USER}_trainclock_node"
HOSTNAME="${USER}_node_dev"
HOME_DIR="/home/dev"

SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PARENT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

docker run -it --rm \
  --name "${CONTAINER_NAME}" \
  --hostname "${HOSTNAME}" \
  --user "$(id -u):$(id -g)" \
  -e TERM="$TERM" \
  -v "$HOME/.ssh:/home/dev/.ssh:ro" \
  -v "$SSH_AUTH_SOCK:/ssh-agent" \
  -e SSH_AUTH_SOCK=/ssh-agent \
  -v "$HOME/.bashrc:$HOME_DIR/.bashrc:ro" \
  -v "$HOME/.vimrc:$HOME_DIR/.vimrc:ro" \
  -v "$HOME/.vim:$HOME_DIR/.vim:ro" \
  -v "$PARENT_DIR/.env:$HOME_DIR/.env" \
  -v "$PARENT_DIR/server:$HOME_DIR/server" \
  --workdir "$HOME_DIR/server" \
  "${IMAGE}" \
  bash -c '
    if [ -f package.json ]; then
      npm install
    fi
    exec bash
  '

